# Generated by Django 3.2.16 on 2023-01-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pets',
            field=models.ManyToManyField(to='pets.Pet'),
        ),
    ]
